language: python

python:
  - "3.8"

jobs:
  include:
    - name: "Mpi modeling on fattree topology"
      script:
        - . build.sh
        - ./stats_run.sh fattree
      
    - name: "Mpi modeling on dragonfly topology"
      script:
        - . build.sh
        - ./stats_run.sh dragonfly
