language: python
sudo: required

matrix:
  include:
    - dist: bionic
      python: 3.8
      env: dist="18.04 LTS bionic"
      
services:
  - docker
  
install:
# Update packages
- sudo apt-get update

# Install tool for visualization
- pip install matplotlib

jobs:
  include:
    - name: "Mpi modeling on fattree topology"
      script:
        - . build.sh
        - echo "Run from $PWD"
        - docker build -t containernet/containernet:ubuntu .
        - docker run --name containernet --rm --privileged --pid='host' -v /var/run/docker.sock:/var/run/docker.sock containernet/containernet ./mininet-mpi/run.sh fattree
      
    - name: "Mpi modeling on dragonfly topology"
      script:
        - . build.sh
        - echo "Run from $PWD"
        - docker build -t containernet/containernet:ubuntu .
        - docker run --name containernet --rm --privileged --pid='host' -v /var/run/docker.sock:/var/run/docker.sock containernet/containernet ./mininet-mpi/run.sh dragonfly
