dist: bionic
language: python
python:
  - "3.8"

services:
  - docker  

install:
# Install libvrt & KVM
- sudo apt-get update && sudo apt-get install -y ansible git aptitude

# Install tool for visualization
- pip install matplotlib

jobs:
  include:
    - name: "Mpi modeling on fattree topology"
      script:
        - . build.sh
        - echo "Run from $PWD"
        - cd ../ansible ; sudo ansible-playbook -i "localhost," -c local install.yml ; cd ../mininet-mpi
        - sudo -E ./run.sh fattree
    - name: "Mpi modeling on dragonfly topology"
      script:
        - . build.sh
        - echo "Run from $PWD"
        - cd ../ansible ; sudo ansible-playbook -i "localhost," -c local install.yml ; cd ../mininet-mpi
        - sudo -E ./run.sh dragonfly

