dist: bionic
language: python
python:
  - "3.8"

install:
# Install libvrt & KVM
- sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

# Download Vagrant & Install Vagrant package
- sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
- sudo dpkg -i vagrant_2.2.14_x86_64.deb

# Vagrant correctly installed?
- vagrant --version

# Install vagrant-libvirt Vagrant plugin
- sudo vagrant plugin install vagrant-libvirt

# Install tool for visualization
- pip install matplotlib

env:
- VAGRANT_DEFAULT_PROVIDER=libvirt

jobs:
  include:
    - name: "Mpi modeling on fattree topology"
      script:
        - . build.sh
        - echo "Run from $PWD"
        - export OVERRIDE_CONTAINERNET_VAGRANTFILE=yes
        - sudo ./stats_run.sh fattree
        - cat all_exec_times
      
    - name: "Mpi modeling on dragonfly topology"
      script:
        - . build.sh
        - echo "Run from $PWD"
        - export OVERRIDE_CONTAINERNET_VAGRANTFILE=yes
        - sudo ./stats_run.sh dragonfly
        - cat all_exec_times
